In [13]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.datasets import Planetoid
from torch_geometric.loader import DataLoader
from torch_geometric.transforms import NormalizeFeatures

provinces = [
    "北京", "天津", "河北", "山西", "内蒙古", "辽宁", "吉林", "黑龙江",
    "上海", "江苏", "浙江", "安徽", "福建", "江西", "山东", "河南",
    "湖北", "湖南", "广东", "广西", "海南", "重庆", "四川", "贵州",
    "云南", "西藏", "陕西", "甘肃", "青海", "宁夏", "新疆"
]

# 给每个省分配一个从 1 开始的编码
province_dict = {province: idx for idx, province in enumerate(provinces)}

In [6]:
import pandas as pd

# 读取 Excel 文件
df = pd.read_excel('./data/solar.xlsx', sheet_name='Sheet1')
df

      year  month province       装机容量        发电量      平均利用小时     日发电系数
0     2019      2       北京    41.9116   0.775365  185.000000  3.135593
1     2019      2       天津   131.5601   1.381381  105.000000  1.779661
2     2019      2       河北  1274.0408  22.489113  176.518000  2.991831
3     2019      2       山西   879.4424  15.829963  180.000000  3.050847
4     2019      2      内蒙古   973.8621  23.314122  239.398600  4.057603
...    ...    ...      ...        ...        ...         ...       ...
1545  2023     11       陕西  1976.7348  22.281277  112.717583  3.757253
1546  2023     11       甘肃  2241.2319  42.300519  188.737805  6.291260
1547  2023     11       青海  2180.8476  26.637418  122.142501  4.071417
1548  2023     11       宁夏  2021.6934  27.015707  133.629102  4.454303
1549  2023     11       新疆  2823.7244  39.614758  140.292578  4.676419

[1550 rows x 7 columns]

In [17]:
df.iloc[:,-5:]

     province       装机容量        发电量      平均利用小时     日发电系数
0          北京    41.9116   0.775365  185.000000  3.135593
1          天津   131.5601   1.381381  105.000000  1.779661
2          河北  1274.0408  22.489113  176.518000  2.991831
3          山西   879.4424  15.829963  180.000000  3.050847
4         内蒙古   973.8621  23.314122  239.398600  4.057603
...       ...        ...        ...         ...       ...
1545       陕西  1976.7348  22.281277  112.717583  3.757253
1546       甘肃  2241.2319  42.300519  188.737805  6.291260
1547       青海  2180.8476  26.637418  122.142501  4.071417
1548       宁夏  2021.6934  27.015707  133.629102  4.454303
1549       新疆  2823.7244  39.614758  140.292578  4.676419

[1550 rows x 5 columns]